version: '3'

services:
  db:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
  web:
    build: ./django_project
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_project:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: web


volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}